notifications:
  slack: easyengine:76AI30tP8P8AcNTaWaQ9ZAT7
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bd77a26eab56de803949
      - https://webhooks.gitter.im/e/e3e2feb8384c77bf1a8a
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

language: bash

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo rm -rf /etc/mysql/
  - sudo bash -c 'echo example.com > /etc/hostname'
  - sudo service hostname restart
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove
  - sudo add-apt-repository -y 'ppa:ondrej/php'
  - sudo apt-get update
  - sudo apt-get -y install php5.6-fpm php5.6-curl php5.6-gd php5.6-imap php5.6-mcrypt php5.6-readline php5.6-mysql php5.6-sqlite3 php5.6-cli php5.6-common php5.6-curl php5.6-mbstring php5.6-bcmath php5.6-recode php5.6-mysql php5.6-opcache php-memcached php-imagick memcached graphviz php-pear php-xdebug php-msgpack php5.6-zip php5.6-xml php5.6-soap php-memcache || ee_lib_error "Unable to install PHP 5.6 packages, exit status " 1
  - sudo apt-get -y install php7.0-fpm php7.0-curl php7.0-gd php7.0-imap php7.0-mcrypt php7.0-readline php7.0-common php7.0-recode php7.0-cli php7.0-mbstring php7.0-bcmath php7.0-mysql php7.0-opcache php7.0-zip php7.0-xml php7.0-soap php7.0-sqlite3 php-memcached  php-imagick php-memcache memcached graphviz php-pear php-xdebug php-msgpack  php-redis || ee_lib_error "Unable to install PHP 5.6 packages, exit status " 1
script:
  - lsb_release -a
  - unset LANG
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - ls -la
  - sudo ln -s $(pwd)/bin/ee /usr/bin/ee
  - chmod +x /usr/bin/ee
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - sudo php composer.phar install

  #- sudo ee --help

  - sudo ee stack install --nginx --debug || tail -n100 testlog.log
  - sudo ee stack install --mysql --debug || tail -n100 testlog.log
  - sudo cat /etc/mysql/conf.d/my.cnf
  - sudo ee stack install --php --debug
  - sudo ee stack install --wpcli --debug
  - wp --allow-root cli version
  - sudo ee stack install --utils --debug


  - sudo ee site create wp.net --type=wp